---
- name: Inicializar variable errors
  set_fact:
    errors: {}

- name: Detectar el sistema operativo
  set_fact:
    os_family: "{{ ansible_os_family }}"
    os_version: "{{ ansible_distribution_version }}"

#- fail:

- name: Depurar información del sistema operativo
  debug:
    msg: "OS Family: {{ os_family }}, OS Version: {{ os_version }}, Distribution: {{ ansible_distribution }}"

- name: Obtener la lista de interfaces de red
  command: ip -o link show
  register: interfaces_output

- name: Parsear las interfaces de red
  set_fact:
    interfaces: "{{ interfaces_output.stdout | regex_findall('\\d+: ([^:]+):') }}"

- name: Depurar lista de interfaces de red
  debug:
    msg: "Interfaces encontradas: {{ interfaces }}"

- name: Verificar errores y paquetes descartados
  block:
    - name: Obtener estadísticas de errores y paquetes descartados
      command: ip -s link show {{ item }}
      loop: "{{ interfaces }}"
      register: interface_stats
      #ignore_errors: true

    - name: Parsear estadísticas de errores y paquetes descartados
      set_fact:
        parsed_stats: "{{ parsed_stats | default([]) + [{
          'iface': item.item,
          'rx_packets': item.stdout_lines[3].split()[0],
          'tx_packets': item.stdout_lines[5].split()[0],
          'rx_errors': item.stdout_lines[3].split()[2],
          'tx_errors': item.stdout_lines[5].split()[2],
          'rx_dropped': item.stdout_lines[3].split()[3],
          'tx_dropped': item.stdout_lines[5].split()[3]
          }] }}"
      loop: "{{ interface_stats.results }}"
      when: item.stdout is not search('errors:|dropped:')

    - name: Mostrar estadísticas de interfaces
      debug:
        var: parsed_stats

- name: Mostrar estadísticas de interfaces con paquetes dropeados o mensaje de interfaz sin paquetes dropeados
  debug:
    msg: >-
      {% set paquetes_dropeados = (item.rx_dropped != "0" or item.tx_dropped != "0") %}
      {% set errores_rx_tx = (item.rx_errors != "0" or item.tx_errors != "0") %}

      {% if not paquetes_dropeados and not errores_rx_tx %}
      Interfaz {{ item.iface }} está bien, no tiene paquetes dropeados ni errores de recepción/transmisión.
      {% elif paquetes_dropeados and not errores_rx_tx %}
      Interfaz {{ item.iface }} tiene paquetes dropeados: RX={{ item.rx_dropped }}, TX={{ item.tx_dropped }}, pero no tiene errores de recepción/transmisión.
      {% elif not paquetes_dropeados and errores_rx_tx %}
      Interfaz {{ item.iface }} no tiene paquetes dropeados, pero tiene errores de recepción/transmisión: RX={{ item.rx_errors }}, TX={{ item.tx_errors }}.
      {% else %}
      Interfaz {{ item.iface }} tiene paquetes dropeados: RX={{ item.rx_dropped }}, TX={{ item.tx_dropped }}, y errores de recepción/transmisión: RX={{ item.rx_errors }}, TX={{ item.tx_errors }}.
      {% endif %}
  loop: "{{ parsed_stats }}"